name: firebase_image
description: A cached Flutter ImageProvider for Firebase Cloud Storage image objects.
version: 1.1.1
homepage: ''
publish_to:  'none' # Remove this line if you wish to publish to pub.dev
null_safety: true

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.11.0
  firebase_storage: ^11.2.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  path_provider: ^2.0.5

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
